import type { Metadata } from "next";
import Image from "next/image";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";

export const metadata: Metadata = { title: "Our Story", description: "Meet Akrivi, her grandmother and the two-generation story behind VELONA." };

export default function AboutPage() {
  return <main className="inner-main"><Header tone="dark" /><section className="inner-hero"><div className="page-shell inner-hero-split"><div><p className="eyebrow">A family story</p><h1>From her hands<br /><em>to mine.</em></h1><p>VELONA brings together a grandmother’s knowledge and her granddaughter’s modern point of view.</p></div><div className="inner-hero-image"><Image src="/velona/craft-squares.jpg" alt="Crochet squares handmade for a VELONA jacket" fill priority sizes="(max-width: 760px) 100vw, 40vw" /></div></div></section><section className="inner-section"><div className="page-shell prose-grid"><p className="big-copy">“We are fortunate to live the dream she carried from a young age, together.”</p><div className="prose-columns"><p>I’m Akrivi, named like my beloved grandmother. From a young age, she dreamed of turning her love for crochet into something she could share with the world. Today, we are lucky enough to live that dream side by side.</p><p>With her experience, patience and passion, and my modern ideas, we bring the traditional and the contemporary closer together. That exchange is at the heart of every VELONA piece.</p><p>Everything is made by hand, with care and attention to detail. Our aim is not only to make beautiful things, but to create feelings, pieces that accompany special moments and help the person wearing them feel unique.</p></div></div></section><section className="drop-banner"><div className="drop-image"><Image src="/velona/making-tools.jpg" alt="Crochet tools and handmade squares in the VELONA studio" fill sizes="(max-width: 760px) 100vw, 55vw" /></div><div className="drop-copy"><p className="eyebrow">The wider circle</p><h2>Learning,<br />making,<br /><em>sharing.</em></h2><p>VELONA also comes alive through workshops, pop-ups and the community around the craft. Because handmade knowledge grows when it is passed on.</p></div></section><Footer /></main>;
}
